package no.nav.amt.lib.models.deltaker

enum class Innsatsgruppe {
    STANDARD_INNSATS,
    SITUASJONSBESTEMT_INNSATS,
    SPESIELT_TILPASSET_INNSATS,
    VARIG_TILPASSET_INNSATS,
    GRADERT_VARIG_TILPASSET_INNSATS,
}
