package no.nav.amt.lib.models.deltakerliste.tiltakstype

enum class Tiltakskode {
    ARBEIDSFORBEREDENDE_TRENING,
    ARBEIDSRETTET_REHABILITERING,
    AVKLARING,
    DIGITALT_OPPFOLGINGSTILTAK,
    GRUPPE_ARBEIDSMARKEDSOPPLAERING,
    GRUPPE_FAG_OG_YRKESOPPLAERING,
    JOBBKLUBB,
    OPPFOLGING,
    VARIG_TILRETTELAGT_ARBEID_SKJERMET,
    HOYERE_UTDANNING,
    ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING,
    ENKELTPLASS_FAG_OG_YRKESOPPLAERING,
    ARBEIDSMARKEDSOPPLAERING, // Vil etter hvert ta over for GRUPPE_ARBEIDSMARKEDSOPPLAERING og ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING
    NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV,
    STUDIESPESIALISERING,
    FAG_OG_YRKESOPPLAERING,
    HOYERE_YRKESFAGLIG_UTDANNING,
    ;

    // Ved lansering av ny forskrift/påmelding av nye typer må vi bruke type feltet GRUPPE/ENKELPLASS istedet for tiltakskode
    fun erEnkeltplass() = this in setOf(HOYERE_UTDANNING, ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING, ENKELTPLASS_FAG_OG_YRKESOPPLAERING)

    @Deprecated("Denne skal antakelig erstattes av lokalt tilpassede versjoner")
    fun toArenaKode() = when (this) {
        ARBEIDSFORBEREDENDE_TRENING -> ArenaKode.ARBFORB
        ARBEIDSRETTET_REHABILITERING -> ArenaKode.ARBRRHDAG
        AVKLARING -> ArenaKode.AVKLARAG
        DIGITALT_OPPFOLGINGSTILTAK -> ArenaKode.DIGIOPPARB
        GRUPPE_ARBEIDSMARKEDSOPPLAERING -> ArenaKode.GRUPPEAMO
        GRUPPE_FAG_OG_YRKESOPPLAERING -> ArenaKode.GRUFAGYRKE
        JOBBKLUBB -> ArenaKode.JOBBK
        OPPFOLGING -> ArenaKode.INDOPPFAG
        VARIG_TILRETTELAGT_ARBEID_SKJERMET -> ArenaKode.VASV
        ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING -> ArenaKode.ENKELAMO
        ENKELTPLASS_FAG_OG_YRKESOPPLAERING -> ArenaKode.ENKFAGYRKE
        HOYERE_UTDANNING -> ArenaKode.HOYEREUTD
        else -> throw IllegalArgumentException("Ukjent tiltakskode: $this")
    }
}
